version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DENO_VERSION: 0.35.0
    image: docker.pkg.github.com/markkovari/deno-template/image:latest
    volumes:
      - "./app:/app"
    command: deno run --allow-net app/app.ts
    ports:
      - "8000:8000"

    # without the created image
    # image: maxmcd/deno:jessie
    # volumes:
    #   - "./app:/app"
    # command: deno run --allow-net app/app.ts
    # ports:
    #   - "8000:8000"
